name: Greg411dotme
favicon: null
layout_spectrum: 0.5357008343562484
typography_spectrum: 0.7406689433846623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.25916806631721556
  lightness: 0.7508371670264751
  saturation: 0.8787394126411527
  rhythmicContrast: 0.3961924840696156
purpose: []
